baseURL = "https://coreylweathers.com/"
# [en, zh-cn, fr, pl, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en-us"
title = "Corey's Syntax & Stories"

# Change the default theme to LoveIt
theme = "LoveIt"

# Permalinks configuration - make posts section use /blog URLs
[permalinks]
  posts = "/posts/:year/:month/:title/"

# Menu config
[menu]
  [[menu.main]]
    identifier = "blog"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = "📝"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Blog posts"
    weight = 1
  # Streams menu item (hidden but kept in config)
  # [[menu.main]]
  #   identifier = "streams"
  #   pre = "🎥"
  #   post = ""
  #   name = "Streams"
  #   url = "/streams/"
  #   title = "Live Streams"
  #   weight = 2
  [[menu.main]]
    identifier = "media"
    pre = "🎤"
    post = ""
    name = "Media"
    url = "/media/"
    title = "Media Appearances"
    weight = 3
  [[menu.main]]
    identifier = "contact"
    pre = "📩"
    post = ""
    name = "Contact"
    url = "/contact/"
    title = "Contact me"
    weight = 4
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "ℹ️About"
    url = "/about/"
    title = "About me"
    weight = 5

# Parameters
[params]
  # LoveIt theme version
  version = "0.2.X"
  # site description
  description = "Corey's Syntax & Stories is where I document my journey—through code, creativity, and life as a developer and parent. From debugging software to navigating the challenges of DevRel and fatherhood, I share insights, lessons, and personal reflections along the way."
  # site keywords
  keywords = ["syntax and stories", "Corey L. Weathers", "Corey Weathers", "coding blog", "developer relations", "devrel insights", "programming stories", "debugging life", "software engineering reflections", "coding lessons", "developer journey", "tech storytelling", "developer advocacy", "work-life balance", "parenting in tech", "coding advice for developers", ".net development", "c# programming", "asp.net core", "blazor development", "dotnet"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/coreylweathers/personal-website"
  # date format
  dateFormat = "2006-01-02"
  # Contact form configuration will be read from HUGO_PARAMS_CONTACT_FORM_ID environment variable

  [params.author]
  name = "Corey"
  email = "corey.weathers@outlook.com"
  link = ""
  
  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/images/icons8-home.svg"
      # title name (can be empty if using logo)
      name = ""
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # whether to use typeit animation for title name
      typeit = false

  # Search config
  [params.search]
    enable = true
    # type of search engine ["lunr", "algolia"]
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
  
  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # title shown in home page
      title = "Corey's Syntax & Stories"
      # subtitle shown in home page
      subtitle = "Corey's Syntax & Stories is where I document my journey—through code, creativity, and life as a developer and parent. From debugging software to navigating the challenges of DevRel and fatherhood, I share insights, lessons, and personal reflections along the way."
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # use profileImage as avatar
      avatarURL = "/images/stencil-headshot.jpg"
      # disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
  
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Corey's Syntax & Stories"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "/favicon.svg"
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-11 tile color
    tileColor = "#da532c"
  
  # Analytics config - uses environment variables
  [params.analytics]
    [params.analytics.google]
      # Google Analytics ID will be read from HUGO_PARAMS_ANALYTICS_GOOGLE_ID environment variable
      id = ""
      respectDoNotTrack = false
    
    [params.analytics.clarity]
      # Microsoft Clarity ID will be read from HUGO_PARAMS_ANALYTICS_CLARITY_ID environment variable
      id = ""

# Custom JavaScript and CSS files
[params.page]
  [params.page.library]
    [params.page.library.js]
      # Custom JS file
      custom = "/js/custom.js"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration for the LoveIt theme
    noClasses = false
  
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
  
  # Social links
  [params.social]
    GitHub = "coreylweathers"
    Linkedin = "coreylweathers"
    X = "coreylweathers"
    Threads = "coreylweathers"
    Discord = "coreylweathers"
    Email = "corey.weathers@outlook.com"  # Footer config

    # New platforms you can add:
    Twitch = "coreylweathers"
    Bluesky = "coreylweathers"
  
    # YouTube options (choose one based on your URL type):
    YouTubeChannel = "coreylweathers"   # for /channel/ID URLs
  [params.footer]
    enable = true
    # Custom copyright content (HTML format is supported)
    custom = 'This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="license">CC BY-NC-ND 4.0</a>'
    # whether to show Hugo and theme info
    hugo = false
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # site creation time
    since = 2025

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

# RSS Configuration
[params.rss]
  # RSS feed description
  description = "Latest blog posts and updates"
  # Number of items in RSS feed
  limit = 20
  # Include full content in RSS feed
  fullContent = true

# Copyright for RSS feeds
copyright = "Copyright © 2025 Corey's Syntax & Stories"