baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "my-minimal-theme"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 60
  [[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 20
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 40
  [[menu.main]]
    name = "Terms of Use"
    url = "/terms/"
    weight = 50

# Parameters
[params]
  profileImage = "/images/stencil-headshot.jpg"